plugin: amazon.aws.aws_ec2
regions:
  - us-west-1
keyed_groups:
  - key: tags.Role
    prefix: role
filters:
  instance-state-name: running
  "tag:Project": iac-webserver
compose:
  ansible_host: public_ip_address
  ansible_user: ec2-user
  instance_tags: tags