name: Destroy Infrastructure

on:
  workflow_dispatch:  # déclenchement manuel

permissions:
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

    steps:
      # Checkout du repo
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download S3 bucket artifact
        uses: actions/download-artifact@v4
        with:
          name: s3-bucket
          path: .

      - name: Load bucket name
        run: |
          echo "S3_BUCKET=$(cat s3_bucket.txt)" >> $GITHUB_ENV
          echo "Bucket S3 utilisé : $S3_BUCKET"

      # Installer Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      # Initialiser Terraform et détruire l'infrastructure
      - name: Terraform Init
        run: |
          cd terraform/main
          terraform init -backend-config="bucket=${{ env.S3_BUCKET }}" \
                         -backend-config="${{ secrets.AWS_DEFAULT_REGION }}" \
                         -backend-config="key=terraform/state.tfstate"
          terraform destroy -auto-approve

      # Confirmer la destruction
      - name: Confirm destruction
        run: echo "Infrastructure détruite avec succès !"